version: '3.9'
services:
  angular:
    build:
      context: ./
      dockerfile: Dockerfile
      target: develop
      args:
      - REPO_PATH=/var/www
    image: angular
    container_name: angular
    hostname: angular
    environment:
    - NODE_ENV=development
    volumes:
    - ./:/var/www
    ports:
    - 4200:4200
    networks:
    - angular

networks:
  angular: